### ISSUE TITLE
Error! No available node version satisfies 'node17'

### ISSUE THREAD

**Issue by cow-killer** [KCGD/proton-compat-cleaner#1]
Running `build.sh` results in this:
```
> pkg@5.4.1
> Error! No available node version satisfies 'node17'
```
Any ideas? Running this script on Arch.

**Comment by KCGD** [comment]
This is likely because pkg couldn't find a prebuilt node.js for node 17. I built this with node 12.18.0, so temporarily downgrading to that version with nvm should fix the issue while building.

https://github.com/nvm-sh/nvm

Once installed, run `nvm use 12.18.0`, `node --version` (make sure it's 12.18.0), then run the build script again.

**Comment by cow-killer** [comment]
Okay, after installing `nvm` I had to run `nvm install 12.18.0`, then I was able to run the build script.

After running the executable I'm unable to change the `compatdata` directory, how can I specify a different path?

**Comment by KCGD** [comment]
The compatdata directory is stored in conf.json (next to the executable). You can change the directory by editing that file. Alternativley, you can just delete conf.json and opt to manually put in the directory when the program asks you.

**Comment by cow-killer** [comment]
```
[INFO]: Found compat dirs:
	0
	1151640
	1271700
	1312960
	1384160
	1414850
	1420170
	1493710
	1580130
	346110
	4112174621
	678950
	881320
	962130
	976730

Scan for game names? [Y/n]: y
[INFO]: Found names for these compats:
	1271700 - possible names: 
		hotwheels
		Saved

	1312960 - possible names: 
		Infinigon
		EpicChef

	1414850 - possible names: 
		GameMill Entertainment
		Nickelodeon All-Star Brawl

	678950 - possible names: 
		DBFighterZ
		Saved
		RED
		Saved

	678950 - possible names: 
		DBFighterZ
		Saved
		RED
		Saved

	962130 - possible names: 
		CEF
		User Data
		Maine
		Saved

	962130 - possible names: 
		CEF
		User Data
		Maine
		Saved


[ERROR]: Couldnt find names for these compats:

[INFO]: Nothing else to do! Please enter a command (see help if unsure) or exit
> 
```
That's the result of running the executable with the correct file path. Nothing seems to happen.

**Comment by KCGD** [comment]
It is working correctly here. It listed out all of the compat folders and the possible names of the game contained in each of them. It doesn't automatically remove games, but in the prompt that opened up, you can use commands like `delete (id)` to get rid of a compat. When you're done, just use `exit` to return to the normal terminal. The commands are also documented in the `help` command once you reach that prompt. I plan to add more in the future :)

**Comment by cow-killer** [comment]
Okay then, I guess I can close this then. Thanks!
